service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  # config: ${file(.secrets.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: sayHello/{name}
          method: get
          cors: true
  bye: 
    handler: handler.bye
    events:
      - http:
          path: sayBye/{name}
          method: get
          cors: true