service: emissions # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  profile: emissions
  environment: 
    PGHOST: ${self:custom.config.PGHOST}
    PGPORT: ${self:custom.config.PGPORT}
    PGDATABASE: ${self:custom.config.PGDATABASE}
    PGUSER: ${self:custom.config.PGUSER}
    PGPASSWORD: ${self:custom.config.PGPASSWORD}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  config: ${file(.secrets.yml)}

functions:
  getEmissionsByYear:
    handler: handler.getEmissionsByYear
    events:
      - http:
          path: getEmissions/{year}
          method: get
          cors: true
          
  getRangeByYear:
    handler: handler.getRangeByYear
    events:
      - http:
          path: getRange/{year}
          method: get
          cors: true